version: '3'
services:
  nginx-frontend:
    container_name: easycmf-nginx
    image: nginx:latest
    environment:
      - "TIMEZONE=Asia/Shanghai"
    ports:
      - 8101:80
    volumes:
      - ./easycmf-ui/dist:/usr/share/nginx/html
      - ./docker/nginx-frontend/servers:/etc/nginx/conf.d

  # easycmf的.env的mysql、redis如果连接到宿主机，地址用：host.docker.internal
  # 如果是连接到docker内服务，则用服务名称，如:redis
  hyperf:
    container_name: easycmf-admin
    image: hyperf/hyperf:8.1-alpine-v3.18-swoole
    restart: always
    environment:
      - "TIMEZONE=Asia/Shanghai"
      - "APP_PROJECT=hyperf"
      - "APP_SYSTEM_ENV=docker"
    working_dir: "/opt/www"
    ports:
      - 9501:9501
      - 9502:9502
      - 9503:9503
    volumes:
      - ./:/opt/www
    entrypoint: ["php", "watch", "-c"]

  # 没有将volumes映射出来，需要持久化自行百度一下

  mysql:
    container_name: easycmf-mysql
    environment:
      - "TZ=Asia/Shanghai"
      - MYSQL_ROOT_PASSWORD=12345678
      - "explicit_defaults_for_timestamp=true"
      - "lower_case_table_names=1"
    image: mysql:5.7
    restart: always
    # command: "--default-authentication-plugin=mysql_native_password"
  redis:
    image: redis
    container_name: easycmf-redis
    restart: always